meta_product_name: "Green Booster"
meta_title: "Green Booster - investing green to make our world better"
meta_description: "Pick a project you want to boost & watch the green impact!"
meta_image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1651&q=80")" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
